# Classifying Fronts 2: In code

In [4]:
# imports
from importlib import reload
import os

import numpy as np
import h5py
import xarray
import pandas

from matplotlib import pyplot as plt
import matplotlib as mpl
from matplotlib.ticker import MultipleLocator
import matplotlib.gridspec as gridspec
import seaborn as sns

from skimage import morphology

from wrangler.plotting import cutout
from wrangler.ogcm import llc as wr_llc

from fronts.dbof import utils as dbof_utils
from fronts.dbof import io as dbof_io
from fronts.finding import dev as finding_dev
from fronts.finding import params as finding_params

# DBOF_dev

In [9]:
dbof_dev_file = '../fronts/runs/dbof/dev/llc4320_dbof_dev.json'

# Load up (old files for laptop ease)

In [2]:
cutouts, tbl = finding_dev.load_test_data()

In [5]:
front_params = finding_params.thin_weak_params

# Example

In [3]:
idx = 500
div_sst, sst, sss, Divb2 = finding_dev.parse_idx(cutouts, idx)

## Find the fronts

In [6]:
fronts = finding_dev.algorithms.fronts_from_divb2(Divb2, **front_params)

## Label

In [7]:
flabels = morphology.label(fronts, connectivity=2)

In [9]:
np.unique(flabels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# Stats

In [40]:
def avg_field(field:np.ndarray, flabels:np.ndarray):
    avgs = []
    Npixs = []
    uni_labels = np.unique(flabels)[1:]
    for ss in uni_labels:
        ipix = flabels == ss
        Npix = np.sum(ipix)
        stat = np.sum(ipix * field) / Npix
        # Save
        avgs.append(stat)
        Npixs.append(Npix)    
    # Return
    return avgs

In [16]:
stats = {}

In [17]:
uni_labels = np.unique(flabels)[1:]
stats['FID'] = uni_labels

## Simple stat (<Divb^2>)

In [42]:
#avg_Divb2 = []
#Npixs = []
#for ss in uni_labels:
#    ipix = flabels == ss
#    Npix = np.sum(ipix)
#    stat = np.sum(ipix * Divb2) / Npix
#    # Save
#    avg_Divb2.append(stat)
#    Npixs.append(Npix)
#
avg_Divb2 = avg_field(Divb2, flabels)
# 
stats['avg_Divb2'] = avg_Divb2

In [19]:
stats['UID'] = [idx]*uni_labels.size

# Length

In [27]:
stats['Npix'] = Npixs

# Lat/lon

In [28]:
# Prepping
R_earth = 6371. # km
circum = 2 * np.pi* R_earth
km_deg = circum / 360.

In [30]:
dx = 2.25 # km/pixel

In [34]:
km_deg

111.19492664455873

## Generate a lat/lon image

In [32]:
lat_0, lon_0 = 32., 110.  # Making these up
cutout_size = 64

In [37]:
np.cos(90.*np.pi/180)

np.float64(6.123233995736766e-17)

In [38]:
lats = lat_0 + np.arange(cutout_size)*dx / km_deg
lat_img = np.outer(lats, np.ones(cutout_size))
# lons (approximate)
lons = lon_0 + np.arange(cutout_size)*dx / (km_deg * np.cos(lat_0*np.pi/180.))
lon_img = np.outer(np.ones(cutout_size), lons)

In [45]:
avg_lats = avg_field(lats, flabels)
avg_lons = avg_field(lons, flabels)

In [46]:
stats['lats'] = avg_lats
stats['lons'] = avg_lons

# Construct a Table

In [47]:
df = pandas.DataFrame(stats)
df

FID     avg_Divb2  UID  Npix       lats        lons
0    1  2.133320e-14  500     6  32.320383  110.377789
1    2  8.636720e-14  500    68  32.626682  110.738970
2    3  2.856012e-14  500     7  32.283286  110.334045
3    4  2.496077e-14  500     7  32.121408  110.143162
4    5  1.613183e-14  500    16  32.752479  110.887307
5    6  1.999716e-14  500    19  32.431319  110.508602
6    7  1.748580e-14  500    10  32.214488  110.252920
7    8  2.316236e-14  500     9  32.002248  110.002651
8    9  1.843156e-14  500     7  32.870094  111.025996

In [24]:
df2 = pandas.DataFrame(stats)
df3 = pandas.concat([df, df2], ignore_index=True)
df3

FID     avg_Divb2  UID
0     1  2.133320e-14  500
1     2  8.636720e-14  500
2     3  2.856012e-14  500
3     4  2.496077e-14  500
4     5  1.613183e-14  500
5     6  1.999716e-14  500
6     7  1.748580e-14  500
7     8  2.316236e-14  500
8     9  1.843156e-14  500
9     1  2.133320e-14  500
10    2  8.636720e-14  500
11    3  2.856012e-14  500
12    4  2.496077e-14  500
13    5  1.613183e-14  500
14    6  1.999716e-14  500
15    7  1.748580e-14  500
16    8  2.316236e-14  500
17    9  1.843156e-14  500

----

In [50]:
np.unique(flabels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [52]:
fmasks = [flabels == flabel for flabel in np.unique(flabels)[1:]]
fmasks = np.stack(fmasks)
fmasks.shape

(9, 64, 64)

In [53]:
Divb2.shape

(64, 64)

In [55]:
np.multiply?

Call signature:  np.multiply(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'multiply'>
File:            ~/miniconda3/envs/ocean/lib/python3.12/site-packages/numpy/__init__.py
Docstring:      
multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Multiply arguments element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays to be multiplied.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where th

In [58]:
tmp = np.multiply(fmasks, Divb2)
tmp.shape

(9, 64, 64)

In [59]:
np.allclose(tmp[0], fmasks[0]*Divb2)

True

In [61]:
tmp2 = fmasks * Divb2
tmp2.shape

(9, 64, 64)

In [62]:
np.allclose(tmp[0], tmp2[0])

True

In [68]:
np.sum(tmp[0])

np.float32(1.2799923e-13)

In [64]:
np.sum(tmp2[0])

np.float32(1.2799923e-13)

In [69]:
np.unique?

Signature:      
np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
    *,
    equal_nan=True,
)
Call signature:  np.unique(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function unique at 0x72dea4246f20>
File:            ~/miniconda3/envs/ocean/lib/python3.12/site-packages/numpy/lib/_arraysetops_impl.py
Docstring:      
Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional
outputs in addition to the unique elements:

* the indices of the input array that give the unique values
* the indices of the unique array that reconstruct the input array
* the number of times each unique value comes up in the input array

Parameters
----------
ar : array_like
    Input array. Unless `axis` is specified, this will be flattened if it
    is not already 1-D.
return_index : bool, optional
    If True, also return the indices of `ar` (along the specified ax

In [71]:
np.sum(fmasks, axis=(1,2))

array([ 6, 68,  7,  7, 16, 19, 10,  9,  7])

In [76]:
tmp3 = np.stack( [np.ones((3,3))])
tmp3.shape

(1, 3, 3)

In [79]:
np.sum(tmp3, axis=(1,2))

array([9.])

----

In [80]:
R_earth = 6371. # km
circum = 2 * np.pi* R_earth
km_deg = circum / 360.

In [87]:
ncutouts = 100
latlons = np.random.uniform(size=(2,ncutouts))
latlons.shape

(2, 100)

In [84]:
cutout_size = 64
dlats = np.arange(cutout_size)*dx / km_deg
dlat_img = np.outer(dlats, np.ones(cutout_size))

In [114]:
lats = latlons[0]
lats.resize(ncutouts,1,1)
lat_imgs = np.ones((ncutouts, cutout_size, cutout_size)) * lats# + dlat_img

In [115]:
lat_imgs[0]

array([[0.22887009, 0.22887009, 0.22887009, ..., 0.22887009, 0.22887009,
        0.22887009],
       [0.22887009, 0.22887009, 0.22887009, ..., 0.22887009, 0.22887009,
        0.22887009],
       [0.22887009, 0.22887009, 0.22887009, ..., 0.22887009, 0.22887009,
        0.22887009],
       ...,
       [0.22887009, 0.22887009, 0.22887009, ..., 0.22887009, 0.22887009,
        0.22887009],
       [0.22887009, 0.22887009, 0.22887009, ..., 0.22887009, 0.22887009,
        0.22887009],
       [0.22887009, 0.22887009, 0.22887009, ..., 0.22887009, 0.22887009,
        0.22887009]])

In [101]:
lats.shape

(100,)

In [102]:
dlat_img.shape

(64, 64)

In [104]:
lons.resize(100,1,1)

In [108]:
np.cos(lons * np.pi/180).shape

(100, 1, 1)

In [116]:
    lon_imgs = np.ones((ncutouts, cutout_size, cutout_size)) * lons
    dlons = np.ones((ncutouts, cutout_size, cutout_size)) / np.cos(lons*np.pi/180.)
    dlons += dlats

In [117]:
dlons.shape

(100, 64, 64)

In [118]:
lon_imgs += dlons